In [1]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [2]:
# load the dataset
df = pd.read_csv('HRDataset.csv')
pd.options.display.max_columns = None
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,PositionID,Position,State,Zip,DOB,Sex,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,DateofHire,DateofTermination,TermReason,EmploymentStatus,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,0,19,Production Technician I,MA,1960,7/10/1983,M,Single,US Citizen,No,White,7/5/2011,NaN,N/A-StillEmployed,Active,Production,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,1,27,Sr. DBA,MA,2148,5/5/1975,M,Married,US Citizen,No,White,3/30/2015,6/16/2016,career change,Voluntarily Terminated,IT/IS,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,1,20,Production Technician II,MA,1810,9/19/1988,F,Married,US Citizen,No,White,7/5/2011,9/24/2012,hours,Voluntarily Terminated,Production,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,0,19,Production Technician I,MA,1886,9/27/1988,F,Married,US Citizen,No,White,1/7/2008,NaN,N/A-StillEmployed,Active,Production,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,1,19,Production Technician I,MA,2169,9/8/1989,F,Divorced,US Citizen,No,White,7/11/2011,9/6/2016,return to school,Voluntarily Terminated,Production,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Sex                         311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   303 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 87.6+ KB

In [4]:
df.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Sex                             0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             207
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [5]:
df[df.ManagerID.isnull()][['ManagerID', "ManagerName", 'Department']]

     ManagerID     ManagerName         Department
19         NaN  Webster Butler  Production
30         NaN  Webster Butler  Production
44         NaN  Webster Butler  Production
88         NaN  Webster Butler  Production
135        NaN  Webster Butler  Production
177        NaN  Webster Butler  Production
232        NaN  Webster Butler  Production
251        NaN  Webster Butler  Production

In [6]:
df[df.ManagerName== 'Webster Butler'][['ManagerID', "ManagerName", 'Department']]

     ManagerID     ManagerName         Department
4         39.0  Webster Butler  Production
19         NaN  Webster Butler  Production
30         NaN  Webster Butler  Production
44         NaN  Webster Butler  Production
65        39.0  Webster Butler  Production
88         NaN  Webster Butler  Production
89        39.0  Webster Butler  Production
105       39.0  Webster Butler  Production
124       39.0  Webster Butler  Production
135        NaN  Webster Butler  Production
151       39.0  Webster Butler  Production
174       39.0  Webster Butler  Production
177        NaN  Webster Butler  Production
198       39.0  Webster Butler  Production
206       39.0  Webster Butler  Production
214       39.0  Webster Butler  Production
232        NaN  Webster Butler  Production
251        NaN  Webster Butler  Production
276       39.0  Webster Butler  Production
280       39.0  Webster Butler  Production
300       39.0  Webster Butler  Production

In [7]:
df['ManagerID'].fillna(39, inplace = True)

In [8]:
df.ManagerID = df.ManagerID.astype('int')

In [9]:
date_columns = ['DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date']
df[date_columns].dtypes

DOB                           object
DateofHire                    object
DateofTermination             object
LastPerformanceReview_Date    object
dtype: object

In [10]:
# I changed the date colunms data type to datecolumns
for i in date_columns:
    df[i] = df[i].astype('datetime64[ns]')

In [11]:
# Rearrange and format
df['Employee_Name'] = (df['Employee_Name'].str.split(',', expand = True).iloc[:,1] 
                    + ' '
                    + df['Employee_Name'].str.split(',', expand = True).iloc[:,0])

In [12]:
# Dropped redundant columns
df.drop(columns = ['MarriedID','MaritalStatusID', 'GenderID', 
                   'Termd', 'PerfScoreID', 'EmpStatusID',
                   'PositionID',], inplace = True)

In [13]:
# reorder of columns
cols_reorder = ['EmpID', 'Employee_Name','Sex', 'MaritalDesc', 'DeptID',
                'FromDiversityJobFairID', 'Salary',
                'Position', 'State', 'Zip', 'DOB', 
                'CitizenDesc', 'HispanicLatino', 'RaceDesc', 'DateofHire',
                'DateofTermination', 'TermReason', 'EmploymentStatus', 'Department',
                'ManagerName', 'ManagerID', 'RecruitmentSource', 'PerformanceScore',
                'EngagementSurvey', 'EmpSatisfaction', 'SpecialProjectsCount',
                'LastPerformanceReview_Date', 'DaysLateLast30', 'Absences'
       ]

In [14]:
df = df[cols_reorder]
df.head()

,EmpID,Employee_Name,Sex,MaritalDesc,DeptID,FromDiversityJobFairID,Salary,Position,State,Zip,DOB,CitizenDesc,HispanicLatino,RaceDesc,DateofHire,DateofTermination,TermReason,EmploymentStatus,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,10026,Wilson K Adinolfi,M,Single,5,0,62506,Production Technician I,MA,1960,1983-07-10,US Citizen,No,White,2011-07-05,NaT,N/A-StillEmployed,Active,Production,Michael Albert,22,LinkedIn,Exceeds,4.60,5,0,2019-01-17,0,1
1,10084,Karthikeyan Ait Sidi,M,Married,3,0,104437,Sr. DBA,MA,2148,1975-05-05,US Citizen,No,White,2015-03-30,2016-06-16,career change,Voluntarily Terminated,IT/IS,Simon Roup,4,Indeed,Fully Meets,4.96,3,6,2016-02-24,0,17
2,10196,Sarah Akinkuolie,F,Married,5,0,64955,Production Technician II,MA,1810,1988-09-19,US Citizen,No,White,2011-07-05,2012-09-24,hours,Voluntarily Terminated,Production,Kissy Sullivan,20,LinkedIn,Fully Meets,3.02,3,0,2012-05-15,0,3
3,10088,Trina Alagbe,F,Married,5,0,64991,Production Technician I,MA,1886,1988-09-27,US Citizen,No,White,2008-01-07,NaT,N/A-StillEmployed,Active,Production,Elijiah Gray,16,Indeed,Fully Meets,4.84,5,0,2019-01-03,0,15
4,10069,Carol Anderson,F,Divorced,5,0,50825,Production Technician I,MA,2169,1989-09-08,US Citizen,No,White,2011-07-11,2016-09-06,return to school,Voluntarily Terminated,Production,Webster Butler,39,Google Search,Fully Meets,5.00,4,0,2016-02-01,0,2

In [15]:
# saving cleaned data
df.to_csv('HR_Employees_Data.csv', index = False)